var nls = {
	title: 'MapScrapy',
	version: 'Versión de ArcGIS Server',
	name: 'Nombre del servicio',
	type: 'Tipo del servicio',
	description: 'Descripción',
	geometryType: 'Tipo de geometría',
	wkid: 'Sistema de referencia',
	count: 'Cantidad de registros totales',
	maxRecordCount: 'Máxima cantidad de registros a descargar',
	commentSuccess: 'Genial, podrá descargar todos los registros del servicio agregado',
	commentWarning1: 'Lo sentimos, la cantidad de registros totales',
	commentWarning2: 'es superior al lìmite de descarga permitido por el servicio; por lo tanto solo podrá descargar ',
	rows: 'registros',
	severalRows: 'La capa no se dibujó por completo. Puede haber demasiados registros para mostrar. Intenta acercar a un área más pequeña.',
	docOficial: 'ver documentación oficial',
	docOficinalurl: 'https://doc.arcgis.com/es/hub/data/server-configuration-details.htm#GUID-D08498B2-096F-4BF5-8D79-AECA9F123098',
	urlfailed: 'Debe ingresar la URL de un servicio o ingresó una URL invalida. por favor verifique la URL del servicio ingresado',
}